version: '3.3'
services:
  rent_manager_api:
    restart: always
    container_name: rent_manager_api
    image: rent_manager_api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - rent_manager
    env_file: 
      - .env
    ports:
      - "5000:5000"

networks:
  rent_manager:
    driver: bridge
