version: '3.3'
services:
  rent_manager_api_prod:
    restart: always
    container_name: rent_manager_api_prod
    image: ${REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}
    networks:
      - rent_manager_prod
    env_file: 
      - .env
    ports:
      - "5000:5000"

networks:
  rent_manager_prod:
    driver: bridge



    
